[server]
headless = true
enableXsrfProtection = true
port = 8501

[theme]
base = "light"
primaryColor = "#0d6efd"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"

[browser]
gatherUsageStats = false
